title: Weaver's First Github Title Header
author: Weaver Marquez
email: fakemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
Weaver Marquez is a mathematician and cousin of Shannon Weaver. She speaks in cryptic messages but never lies.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  weavermarquez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# aesthetics
theme: minima
